version: '3.8'

services:
  my_couchbase:
    build:
      context: .
      dockerfile: database-setup/Dockerfile.couchbase
    container_name: team_availability_couchbase
    environment:
      - CB_CLUSTER_USERNAME=Administrator
      - CB_CLUSTER_PASSWORD=password
      - CB_CLUSTER_RAMSIZE=256
      - CB_CLUSTER_INDEX_RAMSIZE=256
      - CB_CLUSTER_FTS_RAMSIZE=256
      - CB_CLUSTER_QUERY_RAMSIZE=256
      - CB_CLUSTER_ANALYTICS_RAMSIZE=1024
      - CB_CLUSTER_EVENTING_RAMSIZE=256
      - CB_CLUSTER_BUCKET_DEFAULT_RAMSIZE=256
      - CB_CLUSTER_SERVICES=data,index,query,fts,analytics,eventing
    ports:
      - "8091-8097:8091-8097" 
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var

  my_redis:
    image: redis/redis-stack:latest
    container_name: team-availability-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    restart: always

  my_backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: my_backend
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      REDIS_HOST: my_redis
      REDIS_PORT: 6379
      COUCHBASE_HOST: my_couchbase
      COUCHBASE_PORT: 11210
      COUCHBASE_USERNAME: Administrator
      COUCHBASE_PASSWORD: password
      SESSION_SECRET=your-super-secret-session-key-change-this-in-production
      NODE_ENV: local
    depends_on:
      - my_redis
      - my_couchbase
    restart: always
    deploy: 
      replicas: 1

  my_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: my_frontend
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NEXT_PUBLIC_API_URL: http://my_backend:3001
    depends_on:
      - my_backend
    restart: always
    deploy: 
      replicas: 1
  


volumes:
  couchbase_data:
  redis_data:
